### ISSUE TITLE
monitor the Console log output instructs wrong namespace

### ISSUE THREAD

**Issue by rafabene** [verrazzano/docs#291]
At https://verrazzano.io/docs/setup/install/installation/#install-the-verrazzano-platform-operator the documentation says:

> To monitor the Console log output of the installation:

```
$ kubectl -n verrazzano-install logs \
    -f $(kubectl get pod \
    -l job-name=verrazzano-install-my-verrazzano \
    -o jsonpath="{.items[0].metadata.name}")
```

However, the job `verrazzano-install-my-verrazzano` is executed in the default namespace.

**Comment by rosemarymarano** [comment]
The command has been changed and works as expected: 
kubectl logs -n verrazzano-install \
    -f $(kubectl get pod \
    -n verrazzano-install \
    -l app=verrazzano-platform-operator \
    -o jsonpath="{.items[0].metadata.name}") | grep '^{.*}$' \
    | jq -r '."@timestamp" as $timestamp | "\($timestamp) \(.level) \(.message)"'
