### ISSUE TITLE
Review Verrazzano Prerequisites

### ISSUE THREAD

**Issue by rafabene** [verrazzano/docs#293]
At https://verrazzano.io/docs/quickstart/ is said that Verrazzano requires "At least 2 CPUs".  I've tried with 2, 3 and 4 CPUs and Verrazzano won't start because some pods are in the Pending state due to Insufficient CPUs.

I was only able to start Verrazzano with 6 CPUs.

**Comment by markxnelson** [comment]
Thanks for your comment - I think the intention was "2 CPUs per node" and there was an underlying assumption that there'd be at least 3 nodes - hence 6 CPUs.  We'll update that to make it clearer.
