### ISSUE TITLE
app deployment ends up in default namespace

### ISSUE THREAD

**Issue by sschober** [verrazzano/docs#583]
For me

    kubectl apply -f https://raw.githubusercontent.com/verrazzano/verrazzano/v1.3.3/examples/hello-helidon/hello-helidon-comp.yaml

and

    kubectl apply -f https://raw.githubusercontent.com/verrazzano/verrazzano/v1.3.3/examples/hello-helidon/hello-helidon-app.yaml

ended up in the default namespace.

In conssequence, the command:

    kubectl get gateways.networking.istio.io hello-helidon-hello-helidon-appconf-gw \
    -n hello-helidon \
    -o jsonpath='{.spec.servers[0].hosts[0]}'

yielded no success:

    Error from server (NotFound): gateways.networking.istio.io "hello-helidon-hello-helidon-appconf-gw" not found

Instead, I would need to issue the following command:

    kubectl get gateways.networking.istio.io default-hello-helidon-appconf-gw \
    -n default \
    -o jsonpath='{.spec.servers[0].hosts[0]}'

to get to my host:

    hello-helidon-appconf.default.172.18.0.231.nip.io

So, please either update the yaml files with the namespace `hello-helidon`, or update the docs by appending `--namespace hello-helidon` to the kubectl invocation.

**Comment by pfmackin** [comment]
Hi, which doc are you using?  The doc here does specify the namespace: https://verrazzano.io/latest/docs/samples/hello-helidon/

kubectl apply -f https://raw.githubusercontent.com/verrazzano/verrazzano/v1.3.3/examples/hello-helidon/hello-helidon-comp.yaml -n hello-helidon

kubectl apply -f https://raw.githubusercontent.com/verrazzano/verrazzano/v1.3.3/examples/hello-helidon/hello-helidon-app.yaml -n hello-helidon

**Comment by sschober** [comment]
Oh, thanks for the quick reply. On this page it seems to be missing:

https://verrazzano.io/latest/docs/guides/app-deployment/application-deployment-guide/

**Comment by rosemarymarano** [comment]
Thank you. This is now fixed in the App Deployment Guide, https://verrazzano.io/latest/docs/guides/app-deployment/application-deployment-guide/
